// ── Module: kg-store · internal ──────────────────────────────────────────────
// The four structural mutation primitives — the raw verbs a curator uses to
// grow, connect, disconnect, and prune the graph. Each is a single #5
// GraphMutation with its own validate hook. All four run through the same
// framework as upsert_property: two-phase confirm envelope, #6's structural
// rules on the proposed result, #7's audit, #8's role gate.
//
// Deliberately conservative:
//   • create_node MINTS the id server-side (never caller-supplied) so
//     Rule 1's rename check has a stable identity anchor.
//   • link_nodes / unlink_nodes / delete_node work over existing ids;
//     Rule 2 blocks a delete_node that would leave dangling edges, so the
//     caller's flow for a connected node is "unlink first, then delete."
//     No cascade — that's #14.
//   • Composite / recipe operations (add-chapter, split-chapter) are #13.
//   • Editing STRUCTURAL properties of existing nodes (renumber, code
//     change) is a separate future step. create_node sets properties at
//     birth; upsert_property stays wording-only.
//
// Validation beyond #6's two rules is deliberately minimal because there is
// no schema layer in this codebase. See Step 0 findings: LC's own
// domain/range isn't machine-readable in the stored graph (the raw file
// lists schema entity NAMES only; the adapter's parse() drops the LC
// labels and replaces them with internal kinds like "chapter"/"lesson").
// The extra checks we add here observe the CURRENT graph's vocabulary:
//   • create_node's `kind` must be a kind already present in the graph.
//     Introducing an unheard-of kind would be an obvious typo / mistake
//     that Rule 2 wouldn't catch on its own, so we block early. To
//     genuinely introduce a new kind, a future step would add a schema
//     hook to the adapter.
//   • link_nodes's `edgeType` must be an edge type already present.
//     Rejects "hasLesson" / "supports" / other invented type strings.
//     Does NOT enforce domain/range (e.g. hasChild(task→chapter) passes
//     these checks even though it's semantically nonsense) — that judgment
//     is deferred to human review at publish, as the task specifies.
//
// The "known kind / known edge type" set is derived from `base` (the draft
// state the mutation is being applied on top of), so a create_node followed
// by a link_nodes to that new node's kind works — the new node's kind is
// present in the base of the second mutation.

import { randomUUID } from "node:crypto";
import { edgeId } from "./types.js";
import type { MutationEdge, MutationGraph, MutationNode } from "./types.js";
import type { GraphMutation } from "./mutations.js";
import type { WordingAliases } from "../types.js";

// ── Small helpers ────────────────────────────────────────────────────────────

// The set of node kinds currently observed in `base`. Used by create_node.
const observedKinds = (base: MutationGraph): Set<string> =>
  new Set(base.nodes.map((n) => n.type));

// The set of edge types currently observed in `base`. Used by link_nodes.
const observedEdgeTypes = (base: MutationGraph): Set<string> =>
  new Set(base.edges.map((e) => e.type));

// A curator "should also set" list — the wording keys the adapter declares
// for a given kind that are NOT populated (missing or non-string) on the
// proposed new node. Surfaced as WARNINGS on create_node, not errors: a
// freshly created chapter with no title is incomplete but not corrupt, and
// the draft → publish review is the gate for completeness.
function missingWordingKeys(
  kind: string,
  properties: Record<string, unknown>,
  aliases: WordingAliases,
): string[] {
  const perKind = aliases[kind];
  if (!perKind) return [];
  const missing: string[] = [];
  for (const [logicalKey, paths] of Object.entries(perKind)) {
    // The key is "populated" if EVERY declared storage path currently holds
    // a non-empty string on the proposed properties. Any path missing or
    // holding a non-string counts as "not yet populated" for the warning.
    const populated = paths.every((path) => {
      const segments = path.split(".");
      let cur: unknown = properties;
      for (const seg of segments) {
        if (cur === null || typeof cur !== "object") return false;
        cur = (cur as Record<string, unknown>)[seg];
      }
      return typeof cur === "string" && cur.length > 0;
    });
    if (!populated) missing.push(logicalKey);
  }
  return missing;
}

// ── create_node ──────────────────────────────────────────────────────────────
// Mints a fresh randomUUID for the new node's id and adds one node to the
// graph. The id is generated by the TOOL LAYER (see server/structural.ts)
// and threaded through as `newNodeId` in args — the framework then bakes
// that id into the token's args-hash, so a confirm can only apply the same
// dry-run's mint. This keeps `apply` pure (no side-effects like calling
// randomUUID inside): dry-run and confirm compute the same `after`.

export type CreateNodeArgs = {
  kind: string;
  properties: Record<string, unknown>;
  namespace: string;
  aliases: WordingAliases;
  newNodeId: string;             // minted by the tool layer, never by the caller
};

export const createNode: GraphMutation<CreateNodeArgs> = {
  name: "createNode",
  describe: ({ kind }) => `create a new '${kind}' node`,
  validate: (base, _after, args) => {
    const errors: string[] = [];

    // Hard-reject any caller-supplied id sneaking through `properties`.
    // The tool schema doesn't declare an `id` parameter, but a curator
    // could still try to set `properties.id`. Node identity is server-
    // minted; if this route worked, Rule 1's anchor would drift.
    if (args.properties && Object.prototype.hasOwnProperty.call(args.properties, "id")) {
      errors.push(
        `create_node cannot accept a caller-supplied id — node identity is minted server-side. ` +
        `Remove 'id' from properties. (Server minted: '${args.newNodeId}'.)`,
      );
    }

    // The tool layer is responsible for `newNodeId`; if it's absent, the
    // wiring is broken — surface loudly rather than silently corrupt.
    if (typeof args.newNodeId !== "string" || args.newNodeId.length === 0) {
      errors.push(`create_node: newNodeId is missing (tool-layer bug — the server should have minted it).`);
    }

    // Known-kind check (F3 decision — see file header). Deliberately weaker
    // than a real domain/range schema: catches typos and invented kinds,
    // does not enforce cross-kind edge legality.
    const known = observedKinds(base);
    if (!known.has(args.kind)) {
      errors.push(
        `create_node: kind '${args.kind}' is not a known node kind on this namespace. ` +
        `Known kinds: ${[...known].sort().join(", ") || "(none — namespace is empty)"}.`,
      );
    }

    // Id collision — random UUID collisions are astronomically unlikely, but
    // the check is one-line and turns an impossible failure into a clean one.
    if (base.nodes.some((n) => n.id === args.newNodeId)) {
      errors.push(`create_node: id '${args.newNodeId}' already exists in the draft (mint collision — retry).`);
    }

    // Warnings — completeness of wording. Missing wording is INCOMPLETE, not
    // CORRUPT: the draft → publish review is the gate for completeness.
    const warnings: string[] = [];
    if (errors.length === 0) {
      const missing = missingWordingKeys(args.kind, args.properties ?? {}, args.aliases);
      if (missing.length > 0) {
        warnings.push(
          `Node was created without wording for: ${missing.join(", ")}. ` +
          `Use upsert_property to set them before publish, or the reviewer will see an incomplete '${args.kind}'.`,
        );
      }
    }

    return { errors, warnings };
  },
  apply: (base, args) => ({
    nodes: [
      ...base.nodes,
      {
        id: args.newNodeId,
        type: args.kind,
        namespace: args.namespace,
        properties: { ...(args.properties ?? {}) },
      } as MutationNode,
    ],
    edges: base.edges,
  }),
};

// ── link_nodes ───────────────────────────────────────────────────────────────
// Adds one edge between two existing nodes. Edge id is deterministic
// (edgeId(type, from, to)) — this matches how seeded edges are keyed and
// keeps re-linking idempotent-shaped (the same triple always produces the
// same id, so a duplicate link is a validation error, not a stealth
// duplicate). Rule 2 already catches "endpoint doesn't exist" via the
// framework, but we surface a clearer error here so the caller gets one
// blame line instead of two.

export type LinkNodesArgs = {
  edgeType: string;
  fromId: string;
  toId: string;
  properties?: Record<string, unknown>;
  namespace: string;
};

export const linkNodes: GraphMutation<LinkNodesArgs> = {
  name: "linkNodes",
  describe: ({ edgeType, fromId, toId }) => `link '${fromId}' → '${toId}' via '${edgeType}'`,
  validate: (base, _after, args) => {
    const errors: string[] = [];

    // Endpoint existence — surface these here rather than let Rule 2
    // surface a generic "dangling edge" for the same failure.
    const nodeIds = new Set(base.nodes.map((n) => n.id));
    if (!nodeIds.has(args.fromId))
      errors.push(`link_nodes: 'from' node '${args.fromId}' does not exist in the draft.`);
    if (!nodeIds.has(args.toId))
      errors.push(`link_nodes: 'to' node '${args.toId}' does not exist in the draft.`);

    // Known-edge-type check (F3 decision). Rejects "hasLesson" / "supports" /
    // other invented type strings. Does NOT enforce domain/range.
    const knownTypes = observedEdgeTypes(base);
    if (!knownTypes.has(args.edgeType)) {
      errors.push(
        `link_nodes: edge type '${args.edgeType}' is not a known edge type on this namespace. ` +
        `Known edge types: ${[...knownTypes].sort().join(", ") || "(none)"}.`,
      );
    }

    // No self-loop — even if a raw LC edge type could theoretically permit
    // it, none of the current subject vocabularies do, and the reviewer
    // would flag it anyway.
    if (args.fromId === args.toId) {
      errors.push(`link_nodes: self-loops are not allowed ('${args.fromId}' → '${args.fromId}').`);
    }

    // Duplicate edge — same (type, from, to) already exists. Distinct from
    // Rule 1 (which is content-match with a NEW id): here the id would be
    // identical, and the diff would show a "changed" edge with no changes.
    const newEdgeId = edgeId(args.edgeType, args.fromId, args.toId);
    if (base.edges.some((e) => e.id === newEdgeId)) {
      errors.push(`link_nodes: edge '${newEdgeId}' already exists.`);
    }

    return { errors, warnings: [] };
  },
  apply: (base, args) => ({
    nodes: base.nodes,
    edges: [
      ...base.edges,
      {
        id: edgeId(args.edgeType, args.fromId, args.toId),
        type: args.edgeType,
        from: args.fromId,
        to: args.toId,
        namespace: args.namespace,
        properties: { ...(args.properties ?? {}) },
      } as MutationEdge,
    ],
  }),
};

// ── unlink_nodes ─────────────────────────────────────────────────────────────
// Removes one edge by its id. Edge ids are deterministic and cheap to read
// out of a diff / a graph listing, so a single `edgeId` field is enough —
// no need for a (type, from, to) alternative shape.
//
// Removing an edge cannot orphan a node (Rule 2 only cares about surviving
// edges' endpoints, and a removed edge is no longer surviving). It CAN
// leave a node with no incident edges — that's fine in a draft; publish
// review catches completeness.

export type UnlinkNodesArgs = {
  edgeId: string;
};

export const unlinkNodes: GraphMutation<UnlinkNodesArgs> = {
  name: "unlinkNodes",
  describe: ({ edgeId: id }) => `unlink edge '${id}'`,
  validate: (base, _after, args) => {
    const errors: string[] = [];
    if (!base.edges.some((e) => e.id === args.edgeId)) {
      errors.push(`unlink_nodes: edge '${args.edgeId}' does not exist in the draft.`);
    }
    return { errors, warnings: [] };
  },
  apply: (base, args) => ({
    nodes: base.nodes,
    edges: base.edges.filter((e) => e.id !== args.edgeId),
  }),
};

// ── delete_node ──────────────────────────────────────────────────────────────
// Removes one node. Two modes, chosen by the EXPLICIT `force` flag — cascade
// never happens implicitly (#13):
//
//   force=false (default): the safe, raw verb. Rejected if any incident edge
//     would survive (Rule 2 would catch it; validate() surfaces exactly which
//     edges to unlink first). The caller's manual flow stays: unlink each
//     incident edge, then delete.
//
//   force=true: cascade the hasChild SUBTREE in ONE atomic mutation. Removes
//     the target, every hasChild-descendant whose parents are ALL in the
//     removed set (a shared child survives — only its edge to the removed
//     parent drops), and every edge incident to any removed node (this also
//     drops buildsTowards edges touching the target). Siblings and progression
//     neighbours survive. The dry-run diff shows the FULL removed set, and the
//     framework re-runs Rule 1/2 on the result — a correct cascade leaves the
//     graph referentially clean (no new dangling edge).
//
// Dependent-node cascade follows the hasChild edge — the id-based referential
// backbone. A child attached to the target by a maths chapitreNum number ONLY
// (no hasChild edge — a drift state the coverage warnings already flag) is NOT
// in the subtree and would survive; that's an accepted edge case of the
// number/edge denormalization, surfaced as a coverage warning rather than
// silently cascaded.

export type DeleteNodeArgs = {
  nodeId: string;
  force?: boolean;
};

const HAS_CHILD = "hasChild";

// Compute the full set of node ids removed by a force-cascade delete of
// `rootId`: the root plus every hasChild-descendant all of whose hasChild
// parents are themselves in the removed set. Iterates to a fixpoint so a
// child whose last surviving parent gets removed later is still collected.
// Pure over the graph; shared by validate (to report) and apply (to enact).
function cascadeRemovedNodeIds(base: MutationGraph, rootId: string): Set<string> {
  const removed = new Set<string>([rootId]);
  // Parents of each node via hasChild, precomputed.
  const parentsByChild = new Map<string, string[]>();
  const childrenByParent = new Map<string, string[]>();
  for (const e of base.edges) {
    if (e.type !== HAS_CHILD) continue;
    (parentsByChild.get(e.to) ?? parentsByChild.set(e.to, []).get(e.to)!).push(e.from);
    (childrenByParent.get(e.from) ?? childrenByParent.set(e.from, []).get(e.from)!).push(e.to);
  }
  let changed = true;
  while (changed) {
    changed = false;
    for (const removedId of [...removed]) {
      for (const child of childrenByParent.get(removedId) ?? []) {
        if (removed.has(child)) continue;
        const parents = parentsByChild.get(child) ?? [];
        // A child is a dependent orphan only if EVERY hasChild parent is being
        // removed — so a child shared with a surviving parent stays put.
        if (parents.every((p) => removed.has(p))) {
          removed.add(child);
          changed = true;
        }
      }
    }
  }
  return removed;
}

export const deleteNode: GraphMutation<DeleteNodeArgs> = {
  name: "deleteNode",
  describe: ({ nodeId, force }) => (force ? `force-delete node '${nodeId}' and its dependent subtree` : `delete node '${nodeId}'`),
  validate: (base, _after, args) => {
    const errors: string[] = [];
    if (!base.nodes.some((n) => n.id === args.nodeId)) {
      errors.push(`delete_node: node '${args.nodeId}' does not exist in the draft.`);
      return { errors, warnings: [] };
    }
    if (!args.force) {
      // Safe mode: refuse a connected node. Rule 2 would also catch it, but a
      // targeted error tells the caller EXACTLY what to unlink first — or to
      // pass force:true to cascade.
      const incident = base.edges.filter((e) => e.from === args.nodeId || e.to === args.nodeId);
      if (incident.length > 0) {
        errors.push(
          `delete_node: node '${args.nodeId}' still has ${incident.length} incident edge(s): ` +
          `${incident.slice(0, 5).map((e) => e.id).join(", ")}${incident.length > 5 ? ", …" : ""}. ` +
          `delete_node does not cascade by default — either unlink the edges first, or pass force:true to cascade-delete the node and its dependent subtree.`,
        );
      }
    }
    // force=true: no incident-edge error; apply() prunes the whole subtree, and
    // the framework's Rule 1/2 pass proves the result is clean.
    return { errors, warnings: [] };
  },
  apply: (base, args) => {
    if (!args.force) {
      // Safe mode: remove only the node (edges untouched). If it was connected,
      // validate() already blocked; if isolated, this is clean.
      return {
        nodes: base.nodes.filter((n) => n.id !== args.nodeId),
        edges: base.edges,
      };
    }
    // Force mode: prune the dependent subtree + every incident edge.
    const removed = cascadeRemovedNodeIds(base, args.nodeId);
    return {
      nodes: base.nodes.filter((n) => !removed.has(n.id)),
      edges: base.edges.filter((e) => !removed.has(e.from) && !removed.has(e.to)),
    };
  },
};

// ── Convenience helper for the tool layer ────────────────────────────────────
// The tool layer generates the id ONCE per dry-run and threads it through
// args. Confirm-time callers pass the SAME id back so the framework's args-
// hash matches. See src/server/structural.ts for the wiring.
export const mintNodeId = (): string => randomUUID();
